config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/search/:query', to: 'cocktails#search'
    end
  end

  get 'doses/new'
  get 'doses/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:create, :index, :new, :show] do
    resources :doses, only: [:new, :create, :destroy]
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  # validates :imageURL, format: { with: /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}(\/[-a-zA-Z0-9@:%._\+~#=]*)*/i, message: "please enter URL in correct format"}

  include PgSearch::Model
   pg_search_scope :search_by_name_instruction_and_ingredients,
     against: [ :name, :instruction ],
     associated_against: {
      ingredients: [ :name ]
    },
     using: {
       tsearch: { prefix: true, dictionary: "english" }
     }
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  has_many :reviews

  validates :description, presence: true
  # validates :ingredient, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :content, presence: true
  validates :name, presence: true
  validates :rating, inclusion: { in: (0..5).to_a }
  validates :name, uniqueness: { scope: :cocktail }
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API

end

app/controllers/api/v1/cocktails_controller.rb
class Api::V1::CocktailsController < Api::V1::BaseController
  def search
    if params[:query]
      @cocktails = Cocktail.search_by_name_instruction_and_ingredients(params[:query]).first(5)
      render json: @cocktails.map do |cocktail|
        {
          name: cocktail.name,
          instruction: cocktail.instruction,
        }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = Dose.where(cocktail: @cocktail)
    @reviews = Review.where(cocktail: @cocktail)
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render 'new'
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :imageURL)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.find(params[:id])
    @dose.delete
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(cocktail_id: params[:cocktail_id])
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :name, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="position: relative; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path 'nice_bar.jpg' %>);">
  <div class="page-head">
    <h1 class="page-title">World's best cocktail list</h1>
    <%= link_to new_cocktail_path do %>
    <p>+ add a cocktail to the list <i class="fas fa-cocktail"></i></p>
    <% end %>
    <div class="search-bar d-flex justify-content-center" data-controller="search">
      <%= form_tag cocktails_path, method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      id: 'search-typed-text',
      data: {
      action: "keyup->search#fetchResults",
      search_target: "input"
      }
      %>
      <div class="list-group" data-search-target="results">
        <!-- serach results -->
      </div>
      <% end %>
    </div>
  </div>
</div>

<!-- cocktails in cards -->
<div class="cocktail-list">
  <% @cocktails.each_with_index do |cocktail, index| %>
  <%= link_to cocktail_path(cocktail) do %>


  <div class="cocktail-card grow">


    <% if cocktail.photo.attached? %>
    <%= cl_image_tag cocktail.photo.key, alt: "cocktail" %>
    <% else %>
    <%= image_tag cocktail.imageURL, alt: "cocktail" %>
    <% end %>

    <h2><%= index+1 %>. <%= cocktail.name %></h2>
    <div class="stars">
      <% reviews = Review.where(cocktail_id: cocktail.id) %>
      <% reviews.any? ? ratings = reviews.map { |review| review.rating } : ratings = [0] %>
      <% unless  ((ratings.inject(0.0, :+)) / (ratings.count - 1)).nan? || ((ratings.inject(0.0, :+)) / (ratings.count - 1)).infinite? %>
      <% avg = ((ratings.inject(0.0, :+)) / (ratings.count - 1))%>
      <% else %>
      <% avg = 0 %>
      <% end %>
      <% unless avg.floor.zero? %>
        <% avg.floor.times do %>
        <i class="fas fa-star"></i>
        <% end %>
        <% unless (avg.to_f - avg.floor.to_f).zero? %>
        <i class="fas fa-star-half"></i>
        <% end %>
        <% end %>
    </div>
    <p class="rating-avg"><%= avg.round(1) %></p>
  </div>
  <% end %>
  <% end %>

  <%= link_to new_cocktail_path do %>
    <div class="cocktail-card grow">
      <i class="far fa-plus-square plus"></i>
      <h2>Add a new cocktail</h2>
    </div>
  <% end %>
</div>

<!-- footer that doesnt do a thig -->
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This page is powered by booze <i class="fas fa-cocktail"></i>
  </div>
</div>

<!-- <#%= javascript_pack_tag 'index_search' %> -->

app/views/cocktails/new.html.erb
<%= link_to cocktails_path do %>
<i class="back fas fa-long-arrow-alt-left" style="position: absolute; top: 10px; left: 10px; font-size: 50px;"></i>
<% end %>

<div class="form-card">
  <%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :imageURL, label: 'Link for am image', hint: "choose a pretty one 🍸 FYI, uploaded image will be prioritized than the linked one ..." %>
  <%= f.input :instruction, label: 'How do you make this cocktail?', hint: "please be precise 📝" %>
  <%= f.input :photo, as: :file, label: 'Cocktail photo' %>
  <div class="submit-button-wrap">
    <%= f.submit class: 'btn btn-light' %>
  </div>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<% def imagePath %>
  <% if @cocktail.photo.attached? %>
    <% cl_image_path(@cocktail.photo.key) %>
  <% else %>
    <% @cocktail.imageURL %>
  <% end %>
<% end %>



<div class="banner" style="position: relative; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= "#{imagePath}" %>);">
  <%= link_to cocktails_path do %>
    <i class="back fas fa-long-arrow-alt-left" style="position: absolute; top: 10px; left: 10px; font-size: 50px;"></i>
  <% end %>
  <div class="container">
    <h1><%= @cocktail.name %></h1>
    <!-- <#%= link_to class="btn btn-flat" %>  -->
  </div>
</div>

<div class="container">
  <h1 class="mt-5">How to make it</h1>
  <p class="my-5"><%= @cocktail.instruction %></p>
  <% @doses.each do |dose| %>
  <div class="row my-5 border-bottom d-flex flex-column">
    <div class="mb-5 d-flex justify-content-between dose">
      <h4><%= dose.description %> of <%= Ingredient.find(dose.ingredient_id).name %></h4>
      <%= link_to cocktail_dose_path(@cocktail, dose), method: :delete do  %>
      <i class="fas fa-eraser"></i>
      <% end %>
    </div>
  </div>
  <% end %>
  <%= link_to new_cocktail_dose_path(@cocktail) do %>
   <p><i class="fas fa-pencil-alt"></i> edit the recipe</p>
  <% end %>

  <h1 class="mt-5">Reviews</h1>
  <% @reviews.each do |review| %>
    <div class="row my-5 border-bottom d-flex justify-content-between">
      <p><%= review.content %> - <%= review.name %></p>
      <div class="stars d-inline">
      <% review.rating.times do %>
        <i class="fas fa-star"></i>
      <% end %>
      </div>
    </div>
  <% end %>
  <%= link_to new_cocktail_review_path(@cocktail) do %>
  <p><i class="fas fa-pencil-alt"></i> write a review</p>
  <% end %>

  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      This page is powered by booze <i class="fas fa-cocktail"></i>
    </div>
  </div>

</div>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<%= link_to cocktail_path(@cocktail) do %>
<i class="back fas fa-long-arrow-alt-left" style="position: absolute; top: 10px; left: 10px; font-size: 50px;"></i>
<% end %>

<div class="form-card">
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.association :ingredient, hint: "Don't put too much booze otherwise someone is gonna get fuuucked 🥴" %>
    <%= f.input :description, placeholder: "how much do you want?" %>
    <div class="submit-button-wrap">
      <%= f.submit value: 'sprinkle some magic 🪄', class: 'btn btn-light' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Karla:wght@200&family=Spectral:wght@200&display=swap" rel="stylesheet">    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<%= link_to cocktail_path(@cocktail) do %>
<i class="back fas fa-long-arrow-alt-left" style="position: absolute; top: 10px; left: 10px; font-size: 50px;"></i>
<% end %>

<div class="form-card">
  <%= simple_form_for [@cocktail, @review] do |f| %>
  <%= f.input :content, label: 'Review', placeholder: 'It was amazing!'%>
  <%= f.input :name, label: 'Your name'%>
  <%= f.input :rating, hint: 'Give a rating out of five!', collection: 0..5 %>
  <div class="submit-button-wrap">
    <%= f.button :submit, 'review!', class: 'btn btn-light'  %>
  </div>
  <% end %>
</div>